language: python
install: make init
script: make test
cache: pip
matrix:
  include:
  - name: check style
    python: '3.6'
    script: make check
  - name: test py38
    python: '3.6'
    script:
    - make test
    - coverage
    - bash <(curl -s https://codecov.io/bash)
  - name: test py37
    python: '3.7'
  - name: test py38
    python: '3.8'
deploy:
  provider: pypi
  user: __token__
  password:
    secure: MdhNrPuabrSv7xSJhZMWxZj1z4zgzptZ/09BK1GG8h7TlSZ2+prbFcbc2pQtBKjEA5xDYkEucfP5tZtUCFIx5z3aHEzudCRltTFmj8Pp3FEg8RsS5UrVRODPxjPZt9AIXXiYy7XDOjKPaV+8Y8kHm9gEvQHg/Z5KQJ1Ts+69fo6rrzzu65lQQYtx/cmUiU73161Nx3FrcypbGkA2SXbKaSWVa0dEDKmlxTgCDiCUaufb4V2lXOBZsRvpVTuatTRdJU3pc85MPZTprxxUQmChmNK7AsxqLmMXzcpykJwDe6S1dvmNgEygI6VhyfJtV1zUSsVQgFP0gbVkWVXAoQa466hE9PgJ5Ey3OO7NFfi4wtHzF+/RUCaAmlfUVbjp7l5g5BUOhGOuTr8XkCknx0pE2q/ARA5y1lsRSJ6oOFyOmh5CnivsTo4p7vnx8afarqazUgBNvP6nQMaoOPs0G3o5ORsnA0UeBvq1fTJxF2xjiifd4al4QIiAaalcKCa5skcDTLPWx0xs2ou7B6O4RUg01rNSm9sradNe39iNR2uP/GX6T412DldJTA+HS+d6673lT6UzLFHUBVGROrD3/pmAdSsM5ZskXHGtbDisuRpskqSoTyM8YpvoawQ3UK94MADIjskpbtJqBB8eCotqymemlJtTylHISljlAwkHezshNv8=
  on:
    condition: "$TRAVIS_PYTHON_VERSION == '3.7'"
    tags: true
