language: python
install:
  - pip install -r requirements.txt
script:
  - pytest
cache: pip
jobs:
  include:
    - stage: style
      python: '3.6'
      script:
      - black --check .
      - flake8
      - isort --check-only
      - mypy .
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7'
    - stage: test
      python: '3.8'
