language: python
install: make
script: make test
cache: pip
jobs:
  include:
    - stage: style
      python: '3.6'
      script: make check
    - stage: test
      python: '3.6'
      script:
        - make test
        - coverage
        - bash <(curl -s https://codecov.io/bash) # Upload coverage
    - stage: test
      python: '3.7'
    - stage: test
      python: '3.8'
